openapi: 3.0.0
info:
  title: Social Media Poster API
  version: 1.0.0
  description: Backend API for auto-posting to social media
servers:
  - url: http://localhost:3000
paths:
  /api/auth/register:
    post:
      summary: Register a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Registration success
  /api/auth/login:
    post:
      summary: Login user
      responses:
        200:
          description: Login success
